StudyRoom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))  
]
if settings.DEBUG:
     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),

    path('', views.home, name='home'),
    path('rooms/', views.rooms, name='rooms'),
    
    path('room/<str:pk>/', views.room, name='room'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),

    path('create-room/', views.createRoom, name='create-room'),
    path('update-room/<str:pk>/', views.updateRoom, name='update-room'),
    path('delete-room/<str:pk>/', views.deleteRoom, name='delete-room'),

    path('room/<str:pk>/joinUs/', views.joinUs, name='joinUs'),
    # path('delete-message/<str:pk>/', views.deleteMessage, name='delete-message'),
    
    path('update-user/', views.updateUser, name='update-user'),

    path('blogs/', views.blogs, name='blogs'),
    path('blog/<str:pk>/', views.blog, name='blog'),

    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('service/', views.service, name='service'),
    path('faq/', views.faq, name='faq'),


]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatar', null=True)
    bio = models.TextField()
    
    def __str__(self):
        return self.user.username
    
    #pass

class Topic(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='image', null=True)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='image', null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name[0:50]

class Curriculam(models.Model):
    name = models.CharField(max_length=200)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to="files", blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.name[0:50] 

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

class Blog(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='image', null=True)
    name = models.CharField(max_length=200)
    body = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name[0:50]

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]
    
class Contact(models.Model):
    name = models.CharField(max_length=100) 
    email = models.EmailField(max_length=255) 
    subject = models.CharField(max_length=100)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]
                                

base/forms.py
from django.forms import ModelForm
from .models import Room, User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

 
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host','participants']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

base/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Blog, Room, Topic, Message, User, Curriculam, Comment, Contact, Profile
from .forms import RoomForm, UserForm

from django.contrib.auth.models import auth, User

from django.core.mail import send_mail
from django.conf import settings

from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm  # add this


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Invalid User')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Invalid login credentials!!!')
    context = {'page': page}
    return render(request, 'base/login.html', context)


def logoutUser(request):
    logout(request)
    messages.success(request, 'User logged out!!!')
    return redirect('login')


def registerPage(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.success(request, "Registration successful.")
            return redirect('home')
        messages.error(
            request, "Unsuccessful registration, please valid credentials!!!")
    form = NewUserForm()
    return render(request=request, template_name="base/register.html", context={"register_form": form})


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(host__username__icontains=q) |
        Q(description__icontains=q)
    )

    blogs = Blog.objects.all()
    topics = Topic.objects.all()
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))

    context = {'rooms': rooms, 'topics': topics,
               'room_count': room_count, 'room_messages': room_messages, 'blogs': blogs}
    return render(request, 'base/home.html', context)


def rooms(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(host__username__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))

    context = {'rooms': rooms, 'topics': topics,
               'room_count': room_count, 'room_messages': room_messages}
    return render(request, 'base/rooms.html', context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all()
    participants = room.participants.all()
    curriculam = room.curriculam_set.all()
    rooms = Room.objects.all()

    if request.method == 'POST' and request.FILES['file']:
        curriculam = Curriculam.objects.create(
            name=request.POST.get('name'),
            room=room,
            file=request.FILES['file']
        )
        messages.success(request, 'Curriculam Added !!!')
        return redirect('room', pk=room.id)

    context = {'room': room, 'room_messages': room_messages,
               'participants': participants, 'curriculam': curriculam, 'rooms': rooms}
    return render(request, 'base/room.html', context)


def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user': user, 'rooms': rooms,
               'room_messages': room_messages, 'topics': topics}
    return render(request, 'base/profile.html', context)


@login_required(login_url='login')
def createRoom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == 'POST' and request.FILES['image']:
        topic_name = request.POST.get('topic')
        topic, create = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
            image=request.FILES['image'],
        )
        messages.success(request, 'Room created!!!')
        return redirect('create-room')

    context = {'form': form, 'topics': topics}
    return render(request, 'base/create-room.html', context)


@login_required(login_url='/login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    if request.user != room.host:
        messages.warning(request, 'Invalid request!! ')
        return redirect('home')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, create = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        messages.success(request, 'Room updated')
        return redirect('home')

    context = {'form': form, 'topics': topics, 'room': room}
    return render(request, 'base/update-room.html', context)


@login_required(login_url='/login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        messages.warning(request, 'Invalid request!!! ')
        return redirect('home')

    if request.method == 'POST':
        room.delete()
        messages.warning(request, 'Room deleted')
        return redirect('home')
    return render(request, 'base/delete.html', {'obj': room})


@login_required(login_url='/login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        messages.warning(request, 'Invalid request!! ')
        return redirect('home')

    if request.method == 'POST':
        message.delete()
        messages.warning(request, 'Message deleted')
        return redirect('home')
    return render(request, 'base/delete.html', {'obj': message})


@login_required(login_url='/login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()

            messages.success(request, 'Profile Updated Successfully')
            return redirect('update-user')

    return render(request, 'base/update-user.html', {'form': form})


def blogs(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    blogs = Blog.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(host__username__icontains=q) |
        Q(body__icontains=q)
    )

    topics = Topic.objects.all()
    blog_count = blogs.count()
    blog_comments = Comment.objects.filter(Q(blog__topic__name__icontains=q))

    context = {'blogs': blogs, 'topics': topics,
               'blog_comments': blog_comments, 'blog_count': blog_count}
    return render(request, 'base/blogs.html', context)


def blog(request, pk):
    blog = Blog.objects.get(id=pk)
    blogs = Blog.objects.all()
    blog_messages = blog.comment_set.all()

    if request.method == 'POST':
        comment = Comment.objects.create(
            user=request.user,
            blog=blog,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)

        messages.success(request, 'Message sent!!!')
        return redirect('room', pk=room.id)

    context = {'blog': blog, 'blogs': blogs, 'blog_messages': blog_messages}
    return render(request, 'base/blog.html', context)


def contact(request):
    if request.method == 'POST':
        contact = Contact.objects.create(
            name=request.POST.get('name'),
            email=request.POST.get('email'),
            subject=request.POST.get('subject'),
            body=request.POST.get('body')
        )
        messages.success(request, 'Message sent')

        subject = 'StudyRoom Online Lerning Community Message'
        message = f'Hi {contact.name}, thank you for your message to StudyRoom Online Lerning Community'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [contact.email]
        send_mail(subject, message, email_from, recipient_list)

    context = {}
    return render(request, 'base/contact.html', context)


def about(request):
    context = {}
    return render(request, 'base/about.html', context)


def service(request):
    context = {}
    return render(request, 'base/service.html', context)


def faq(request):
    context = {}
    return render(request, 'base/faq.html', context)

def joinUs(request, pk):
    room = Room.objects.get(id=pk)

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)

        messages.success(request, 'Message sent !!!')
        return redirect('room', pk=room.id)

    context = {'room': room}

base/templates/base/acc_active.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}  
{% endautoescape %}  

base/templates/base/blog.html
{% extends 'main.html' %}

{% block content %}

{% load static %}

<div class="page-header" style="background: url({%static 'assets/img/banner1.jpg' %});">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-wrapper">
                    <h2 class="product-title">Blog Details</h2>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'home' %}">Home /</a></li>
                        <li class="current">Blog Details</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="content" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-xs-12">

                <div class="blog-post single-post">

                    <div class="post-thumb">
                        <a href="#"><img class="img-fluid" src="{{blog.image.url}}" alt=""></a>
                        <div class="hover-wrap">
                        </div>
                    </div>


                    <div class="post-content">
                        <h2 class="post-title"><a href="#l">{{blog.name}}</a></h2>
                        <div class="meta">
                            <span class="meta-part"><a href="#"><i class="lni-user"></i>{{blog.host}}</a></span>
                            <span class="meta-part"><a href="#"><i class="lni-alarm-clock"></i>{{blog.created | timesince}}</a></span>
                            <span class="meta-part"><a href="#"><i class="lni-folder"></i>{{blog.topic}}</a></span>
                            <span class="meta-part"><a href="#"><i class="lni-comments-alt"></i>{{blog.}} Comments</a></span>
                        </div>
                        <div class="entry-summary">
                            <p>{{blog.body}}</p>
                        </div>
                    </div>

                </div>


                <div id="comments">
                    <div class="comment-box">
                        <h3>Comments</h3>
                        <ol class="comments-list">
                            <li>
                                <div class="media">
                                    <div class="thumb-left">
                                        <a href="#">
                                            <img class="img-fluid" src="{%static 'assets/img/blog/user1.jpg' %}" alt="">
                                        </a>
                                    </div>
                                    <div class="info-body">
                                        <div class="media-heading">
                                            <h4 class="name">Larsen Mortin</h4>
                                            <span class="comment-date"><i class="lni-alarm-clock"></i> June 21,
                                                2018</span>
                                            <a href="#" class="reply-link"><i class="lni-reply"></i> Reply</a>
                                        </div>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis, nemo
                                            ipsam eum illo minus voluptatibus ipsa nulla, perferendis aliquid
                                            aperiam beatae nihil sapiente eaque atque nesciunt perspiciatis ex
                                            saepe, quibusdam..</p>
                                    </div>
                                </div>
                                <ul>
                                    <li>
                                        <div class="media">
                                            <div class="thumb-left">
                                                <a href="#">
                                                    <img class="img-fluid" src="{%static 'assets/img/blog/user2.jpg' %}" alt="">
                                                </a>
                                            </div>
                                            <div class="info-body">
                                                <div class="media-heading">
                                                    <h4 class="name">Albert Johnes</h4>
                                                    <span class="comment-date"><i class="lni-alarm-clock"></i> June
                                                        21, 2018</span>
                                                    <a href="#" class="reply-link"><i class="lni-reply"></i>
                                                        Reply</a>
                                                </div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                                    Officiis, nemo ipsam eum illo minus voluptatibus ipsa nulla,
                                                    perferendis aliquid aperiam beatae nihil sapiente eaque atque
                                                    nesciunt perspiciatis ex saepe, quibusdam..</p>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <div class="media">
                                    <div class="thumb-left">
                                        <a href="#">
                                            <img class="img-fluid" src="{%static 'assets/img/blog/user3.jpg' %}" alt="">
                                        </a>
                                    </div>
                                    <div class="info-body">
                                        <div class="media-heading">
                                            <h4 class="name">Steven Hawkins</h4>
                                            <span class="comment-date"><i class="lni-alarm-clock"></i> June 21,
                                                2018</span>
                                            <a href="#" class="reply-link"><i class="lni-reply"></i> Reply</a>
                                        </div>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis, nemo
                                            ipsam eum illo minus voluptatibus ipsa nulla, perferendis aliquid
                                            aperiam beatae nihil sapiente eaque atque nesciunt perspiciatis ex
                                            saepe, quibusdam..</p>
                                    </div>
                                </div>
                            </li>
                        </ol>

                        <div id="respond">
                            <h2 class="respond-title">Leave A Comment</h2>
                            <form action="#">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-xs-12">
                                        <div class="form-group">
                                            <input id="author" class="form-control" name="author" type="text"
                                                value="" size="30" placeholder="Your Name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-xs-12">
                                        <div class="form-group">
                                            <input id="email" class="form-control" name="author" type="text"
                                                value="" size="30" placeholder="Your E-Mail">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12col-xs-12">
                                        <div class="form-group">
                                            <textarea id="comment" class="form-control" name="comment" cols="45"
                                                rows="8" placeholder="Massage..."></textarea>
                                        </div>
                                        <button type="submit" id="submit" class="btn btn-common">Post
                                            Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>

            </div>

            <aside id="sidebar" class="col-lg-4 col-md-12 col-xs-12 right-sidebar">             

                <div class="widget widget-popular-posts">
                    <h4 class="widget-title">Recent Posts</h4>
                    <ul class="posts-list">
                        {% for blog in blogs.all|slice:5 %}
                        <li>
                            <div class="widget-thumb">
                                <a href="{% url 'blog' blog.id %}"><img src="{{blog.image.url}}" alt="" /></a>
                            </div>
                            <div class="widget-content">
                                <a class="text-dark" href="{% url 'blog' blog.id %}">{{blog.name}}</a>
                                <span><i class="icon-calendar"></i>{{blog.created | timesince}}</span>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget">
                    <h4 class="widget-title">Advertisement</h4>
                    <div class="add-box">
                        <img src="{%static 'assets/img/img1.jpg' %}" alt="">
                    </div>
                </div>
            </aside>

        </div>
    </div>
</div>

{% endblock %}

base/templates/base/blogs.html
{% extends 'main.html' %}

{% block content %}

{% load static %}

<div class="page-header" style="background: url({% static 'assets/img/banner1.jpg' %});">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-wrapper">
                    <h2 class="product-title">Blog</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Home /</a></li>
                        <li class="current">Blog</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="content" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-xs-12">
                {% for blog in blogs %}
                <div class="blog-post">

                    <div class="post-thumb">
                        <a href="#"><img class="img-fluid" src="{{blog.image.url}}" alt=""></a>
                        <div class="hover-wrap"></div>
                    </div>


                    <div class="post-content">
                        <div class="meta">
                            <span class="meta-part"><a href="#"><i class="lni-user"></i> {{blog.topic}}</a></span>
                            <span class="meta-part"><a href="#"><i class="lni-alarm-clock"></i>{{blog.created | timesince}}</a></span>
                            <span class="meta-part"><a href="#"><i class="lni-folder"></i> Sticky</a></span>
                            <span class="meta-part"><a href="#"><i class="lni-comments-alt"></i> 1
                                    Comments</a></span>
                        </div>
                        <h2 class="post-title"><a href="{% url 'blog' blog.id %}">{{blog.name}}</a></h2>
                        <div class="entry-summary">
                            <p>{{blog.body | truncatechars:200}}</p>
                        </div>
                        <a href="{% url 'blog' blog.id %}" class="btn btn-common">Read More</a>
                    </div>

                </div>
                {% endfor %}
                <div class="pagination-bar">
                    <nav>
                        <ul class="pagination">
                            <li class="page-item"><a class="page-link active" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Next</a></li>
                        </ul>
                    </nav>
                </div>

            </div>

            <aside id="sidebar" class="col-lg-4 col-md-12 col-xs-12 right-sidebar">

                <div class="widget_search">
                    <form role="search" id="search-form">
                        <input type="search" class="form-control" autocomplete="off" name="s"
                            placeholder="Search..." id="search-input" value="">
                        <button type="submit" id="search-submit" class="search-btn"><i
                                class="lni-search"></i></button>
                    </form>
                </div>

                <div class="widget categories">
                    <h4 class="widget-title">All Categories</h4>
                    <ul class="categories-list">
                        <li>
                            <a href="{% url 'blogs' %}">
                                <i class="lni-dinner"></i>
                                All Topics <span class="category-counter">({{topics.count}})</span>
                            </a>
                        </li>
                        {% for topic in topics %}
                        <li>
                            <a href="{% url 'blogs' %}?q={{topic.name}}">
                                <i class="lni-control-panel"></i>
                                {{topic.name}} <span class="category-counter">({{topic.blog_set.all.count}})</span>
                            </a>
                        </li>
                        {% endfor %}
                        
                    </ul>
                </div>

                <div class="widget widget-popular-posts">
                    <h4 class="widget-title">Recent Posts</h4>
                    <ul class="posts-list">
                        {% for blog in blogs.all|slice:5 %}
                        <li>
                            <div class="widget-thumb">
                                <a href="{% url 'blog' blog.id %}"><img src="{{blog.image.url}}" alt="" /></a>
                            </div>
                            <div class="widget-content">
                                <a class="text-dark" href="{% url 'blog' blog.id %}">{{blog.name}}</a>
                                <span><i class="icon-calendar"></i>{{blog.created | timesince}}</span>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget">
                    <h4 class="widget-title">Advertisement</h4>
                    <div class="add-box">
                        <img src="{% static 'assets/img/img1.jpg' %}" alt="">
                    </div>
                </div>
            </aside>

        </div>
    </div>
</div>

{% endblock %}